spring:
  application:
    name: sorokchat-backend
server:
  port: 8080
springdoc:
  api-docs:
    resolve-schema-properties: false
    resolve-extensions-properties: false
  swagger-ui:
    url: /openapi.yaml
