openapi: 3.1.0
info:
  title: Sorokchat
  description: Український захищений месенджер
  version: 1.0.0
components:
  schemas:
    GetUserPayload:
      description: Данні для отримання користувача
      type: object
      required:
        - id
        - login
        - displayName
        - role
      properties:
        id:
          type: integer
          description: Унікальний ідентифікатор користувача
          example: 1
        login:
          type: string
          description: Логін користувача
          example: andrey
        displayName:
          type: string
          description: Видиме ім'я користувача
          example: Сороковський Андрій
        role:
          type: string
          description: Роль користувача
          example: USER
    RegisterPayload:
      description: Данні для реєстрації користувача
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
          description: Логін користувача
          example: andrey
        password:
          type: string
          description: Пароль користувача
          example: <PASSWORD>
        displayName:
          type: string
          description: Видиме ім'я користувача
          example: Сороковський Андрій
    LoginPayload:
      type: object
      description: Данні для входу користувача у систему
      required:
        - login
        - password
      properties:
        login:
          type: string
          description: Логін користувача
          example: andrey
        password:
          type: string
          description: Пароль користувача
          example: <PASSWORD>
    ErrorPayload:
      description: Помилка при взаємодії
      type: object
      required:
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          description: URI-посилання на тип помилки. `about:blank` означає, що специфічний тип не визначено
          example: 'http://localhost:8080/errors/bad-request'
        title:
          type: string
          description: Зрозумілий, короткий опис помилки
          example: Не коректні данні
        status:
          type: integer
          description: HTTP статус код помилки
          example: 400
        detail:
          type: string
          description: Детальне пояснення помилки
          example: Не коректні данні авторизації
        instance:
          type: string
          description: URI, що вказує на конкретний запит, який спричинив помилку
          example: '/authorization/login'
        properties:
          type: object
          description: Додаткові поля помилки
          additionalProperties: true
  responses:
    AuthorizedResponse:
      description: Користувача авторизувався у системі
      headers:
        Location:
          $ref: '#/components/headers/Location'
        Authorization:
          $ref: '#/components/headers/Authorization'
    ForbiddenResponse:
      description: Немає доступу
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorPayload'
    BadRequestResponse:
      description: Некоректні данні
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorPayload'
    ConflictResponse:
      description: Конфлікт даних
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorPayload'
    UnauthorizedResponse:
      description: Не авторизовано
      headers:
        WWW-Authenticate:
          $ref: '#/components/headers/WWW-Authenticate'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorPayload'
    ProfileResponse:
      description: Успішне отримання користувача
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetUserPayload'
  headers:
    Location:
      description: Посилання на авторизованого користувача
      schema:
        type: string
        format: uri
        required: true
        example: 'http://localhost:8080/authorization/profile'
    Authorization:
      description: JWT Token для авторизація
      schema:
        type: string
        required: true
        example: Bearer <TOKEN>
    WWW-Authenticate:
      description: Метод автентифікації
      schema:
        type: string
        required: true
        example: Bearer
servers:
  - url: 'http://localhost:8080'
paths:
  /authorization/register:
    post:
      tags:
        - Авторизація
      summary: Реєстрація користувача
      description: Реєструє користувача у система
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterPayload'
      responses:
        201:
          $ref: '#/components/responses/AuthorizedResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        403:
          $ref: '#/components/responses/ForbiddenResponse'
        409:
          $ref: '#/components/responses/ConflictResponse'
  /authorization/login:
    post:
      tags:
        - Авторизація
      summary: Вхід
      description: Вхід користувача у систему
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginPayload'
      responses:
        201:
          $ref: '#/components/responses/AuthorizedResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        403:
          $ref: '#/components/responses/ForbiddenResponse'
  /authorization/profile:
    get:
      tags:
        - Авторизація
      summary: Профіль
      description: Отримання авторизованого користувача
      operationId: profile
      responses:
        200:
          $ref: '#/components/responses/ProfileResponse'
        401:
          $ref: '#/components/responses/UnauthorizedResponse'
  /authorization/logout:
    delete:
      tags:
        - Авторизація
      summary: Вихід
      description: Вихід користувача із системи
      operationId: logout
      responses:
        204:
          description: Успішний вихід
        401:
          $ref: '#/components/responses/UnauthorizedResponse'